import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F9FAFB",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 16,
        paddingHorizontal: 20,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: "#E5E7EB",
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#F3F4F6",
        alignItems: "center",
        justifyContent: "center",
        marginRight: 16,
    },
    headerContent: {
        flex: 1,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: "#111827",
        marginBottom: 8,
    },
    progressContainer: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    progressBar: {
        flex: 1,
        height: 6,
        backgroundColor: "#E5E7EB",
        borderRadius: 3,
        overflow: "hidden",
    },
    progressFill: {
        height: "100%",
        backgroundColor: "#2563EB",
        borderRadius: 3,
    },
    progressText: {
        fontSize: 13,
        fontWeight: "600",
        color: "#2563EB",
        minWidth: 40,
    },
    form: {
        padding: 20,
        paddingBottom: 40,
    },
    inputContainer: {
        marginBottom: 24,
    },
    labelRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 8,
    },
    label: {
        fontSize: 14,
        fontWeight: "600",
        color: "#374151",
    },
    required: {
        color: "#EF4444",
    },
    errorText: {
        fontSize: 12,
        color: "#EF4444",
        fontWeight: "500",
    },
    inputWrapper: {
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 2,
        borderColor: "#E5E7EB",
        backgroundColor: "#fff",
        borderRadius: 12,
        paddingHorizontal: 16,
        minHeight: 56,
    },
    inputWrapperError: {
        borderColor: "#EF4444",
        backgroundColor: "#FEF2F2",
    },
    inputWrapperFilled: {
        borderColor: "#2563EB",
    },
    inputIcon: {
        marginRight: 12,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: "#111827",
        padding: 0,
        paddingVertical: 16,
    },
    inputMultiline: {
        paddingTop: 16,
        paddingBottom: 16,
        minHeight: 80,
        textAlignVertical: "top",
    },
    suggestionsContainer: {
        marginTop: 12,
        padding: 12,
        backgroundColor: "#F9FAFB",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E5E7EB",
    },
    suggestionsTitle: {
        fontSize: 13,
        fontWeight: "600",
        color: "#6B7280",
        marginBottom: 8,
    },
    suggestionsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    suggestionChip: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: "#fff",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#D1D5DB",
    },
    suggestionText: {
        fontSize: 14,
        color: "#374151",
        fontWeight: "500",
    },
    typeSuggestionsContainer: {
        marginTop: 12,
        backgroundColor: "#F9FAFB",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E5E7EB",
        overflow: "hidden",
    },
    typeSuggestionItem: {
        flexDirection: "row",
        alignItems: "center",
        padding: 16,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: "#E5E7EB",
        gap: 12,
    },
    typeSuggestionText: {
        fontSize: 16,
        color: "#374151",
        fontWeight: "500",
    },
    submitButton: {
        backgroundColor: "#2563EB",
        paddingVertical: 18,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        marginTop: 32,
        shadowColor: "#2563EB",
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
        elevation: 4,
    },
    submitButtonDisabled: {
        backgroundColor: "#9CA3AF",
        shadowOpacity: 0,
    },
    submitButtonText: {
        color: "#fff",
        fontSize: 17,
        fontWeight: "700",
    },
    requiredNote: {
        textAlign: "center",
        color: "#9CA3AF",
        fontSize: 13,
        marginTop: 20,
        fontStyle: "italic",
    },
});